POST http://localhost:8080/auth/register?username=testuser&password=test123

###
POST http://localhost:8080/auth/login?username=testuser&password=test123

###

POST http://localhost:8080/messages/send?senderId=1&recipientId=2&content=Hello!

###

GET http://localhost:8080/messages?senderId=1&recipientId=2